## Date : 25.09.26
## Pandas 🐼
<pre>
    Pandas is a python library used to store, organized, analyze and manipulate data in table-like format.
    We can read and create dataset using pandas.
</pre>

<pre>
    Series : 
    -> Multiple Row Single Column
    
    DataFrame : 
    -> Multiple column and Rows 
</pre>`

In [1]:
# importing pandas
import pandas as pd

In [2]:
# Version check of pandas
print(pd.__version__)

2.2.2

In [30]:
# Creating a series : 
s = pd.Series(['a','b','c','d'])
print(s)
print("Types of s : ", type(s))
print("Address of s : ",id(s))

0    a
1    b
2    c
3    d
dtype: object
Types of s :  <class 'pandas.core.series.Series'>
Address of s :  1740302923776

In [31]:
# Assign index position 
s1 = pd.Series(['a','b','c','d'], index=[10,20,30,40])
print("index  value \n",s1)

index  value
 10    a
20    b
30    c
40    d
dtype: object

In [32]:
s2 = pd.Series(['arjun','bhai','chua','don'], index=['a','b','c','d','e'])
print("index  value \n",s2)

ValueError: Length of values (4) does not match length of index (5)

In [33]:
s2 = pd.Series(['arjun','bhai','chua','don','eye','future'], index=[10,20,20,30,40,50])
print("index  value \n",s2)
print("Indexing s2[20] : \n",s2[20])

index  value
 10     arjun
20      bhai
20      chua
30       don
40       eye
50    future
dtype: object
Indexing s2[20] :
 20    bhai
20    chua
dtype: object

In [34]:
# Slicing of pandas
print("s2[0:3:1] : \n", s2[0:3:1])
print("s2[::-1] : \n", s2[::-1])

s2[0:3:1] :
 10    arjun
20     bhai
20     chua
dtype: object
s2[::-1] :
 50    future
40       eye
30       don
20      chua
20      bhai
10     arjun
dtype: object

In [35]:
s2[10:30:1]

Series([], dtype: object)

In [36]:
# .loc : look at the INDEX
# if the change the index position then used the .loc for access as per the user indexing position
s2.loc[10:40:1]

10    arjun
20     bhai
20     chua
30      don
40      eye
dtype: object

In [37]:
print(s2[20])

20    bhai
20    chua
dtype: object

In [38]:
# Tuple to series  
t = pd.Series((10,20,30,40))
print(t)
print(t[2])
print(t[0:3:1])

0    10
1    20
2    30
3    40
dtype: int64
30
0    10
1    20
2    30
dtype: int64

In [39]:
print(t[-2])
# we can't use -ve indexing on a Series.

KeyError: -2

In [40]:
# for -ve indexing we can use iloc
print(t.iloc[-1])
print(t.iloc[-2])

40
30

In [41]:
# list to Series
l = pd.Series([100,200,300,400])
print(l)
print(l.iloc[-1])

0    100
1    200
2    300
3    400
dtype: int64
400

In [42]:
# set to Series
se = pd.Series({10,20,30,40,50})
se

TypeError: 'set' type is unordered

In [43]:
# Dictionary to series :
D = pd.Series({'a' : 1,'b' : 2, 'c' : 3, 'd' : 4})
print(D)

a    1
b    2
c    3
d    4
dtype: int64

In [44]:
E = pd.Series({'a' : 1,'b' : 2, 'c' : 3, 'd' : 4}, index={'e','b','f','d'})
print(E)

e    NaN
d    4.0
b    2.0
f    NaN
dtype: float64

In [45]:
print(E[2])
print(E['b'])
print(E['d'])

2.0
2.0
4.0

C:\Users\murmu\AppData\Local\Temp\ipykernel_4188\3913823042.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(E[2])

In [46]:
print(E[0:3:1])
print(E[::1])
print(E[::-1])

e    NaN
d    4.0
b    2.0
dtype: float64
e    NaN
d    4.0
b    2.0
f    NaN
dtype: float64
f    NaN
b    2.0
d    4.0
e    NaN
dtype: float64

In [47]:
print(E['a':'d':1])

KeyError: 'a'

### DataFrame:
<b> </b>

In [55]:
# creating a DataFrame : 
DF = {'Name' : ['Arjun','Site','Hari','Subha','Bhagya'],
    'Roll': [21,31,41,51,61],
     'Skills': ['Cooking','Travel','Sleeping','Study','Foodie']
     }
print(DF)

{'Name': ['Arjun', 'Site', 'Hari', 'Subha', 'Bhagya'], 'Roll': [21, 31, 41, 51, 61], 'Skills': ['Cooking', 'Travel', 'Sleeping', 'Study', 'Foodie']}

In [56]:
data = pd.DataFrame(DF)
data

     Name  Roll    Skills
0   Arjun    21   Cooking
1    Site    31    Travel
2    Hari    41  Sleeping
3   Subha    51     Study
4  Bhagya    61    Foodie

In [11]:
# indexing
print("4th index name : ",data.Name[3])
print("3th index name : ",data.Name[2])
print("4th index Skills : ",data.Skills[3])
print("3th index Skills : ",data.Skills[2])
print("4th index Roll : ",data.Roll[3])
print("3th index Roll : ",data.Roll[2])

4th index name :  Subha
3th index name :  Hari
4th index Skills :  Study
3th index Skills :  Sleeping
4th index Roll :  51
3th index Roll :  41

In [12]:
# Slicing
print(data[1:3:1])
print("\n")
print(data[0:3:2])

   Name  Roll    Skills
1  Site    31    Travel
2  Hari    41  Sleeping


    Name  Roll    Skills
0  Arjun    21   Cooking
2   Hari    41  Sleeping

In [13]:
print(data[4:5:1])

     Name  Roll  Skills
4  Bhagya    61  Foodie

In [14]:
# iloc(integer Location) : used for slicing on a DataFrame
# iloc[row,column]
data.iloc[3,::]

Name      Subha
Roll         51
Skills    Study
Name: 3, dtype: object

In [15]:
# column
data.iloc[::,2]

0     Cooking
1      Travel
2    Sleeping
3       Study
4      Foodie
Name: Skills, dtype: object

In [16]:
data.iloc[::-2,::]

     Name  Roll    Skills
4  Bhagya    61    Foodie
2    Hari    41  Sleeping
0   Arjun    21   Cooking

In [17]:
data.iloc[::-1,::-1]

     Skills  Roll    Name
4    Foodie    61  Bhagya
3     Study    51   Subha
2  Sleeping    41    Hari
1    Travel    31    Site
0   Cooking    21   Arjun

In [18]:
print(data.Name)
print(data.Skills)
print(data.Roll)

0     Arjun
1      Site
2      Hari
3     Subha
4    Bhagya
Name: Name, dtype: object
0     Cooking
1      Travel
2    Sleeping
3       Study
4      Foodie
Name: Skills, dtype: object
0    21
1    31
2    41
3    51
4    61
Name: Roll, dtype: int64

In [19]:
data

     Name  Roll    Skills
0   Arjun    21   Cooking
1    Site    31    Travel
2    Hari    41  Sleeping
3   Subha    51     Study
4  Bhagya    61    Foodie

In [20]:
# head : head it repesent the top rows (bydefault 5)
data.head(3)

    Name  Roll    Skills
0  Arjun    21   Cooking
1   Site    31    Travel
2   Hari    41  Sleeping

In [21]:
# tail : it represent the bottom rows (bydefault 5)
print(data.tail())
data.tail(2)

     Name  Roll    Skills
0   Arjun    21   Cooking
1    Site    31    Travel
2    Hari    41  Sleeping
3   Subha    51     Study
4  Bhagya    61    Foodie

     Name  Roll  Skills
3   Subha    51   Study
4  Bhagya    61  Foodie

In [22]:
# sample : represent random row/sample (bydefault one)
print("1st Run : \n",data.sample())
print("2nd Run : \n",data.sample())
print("3rd Run : \n",data.sample())

1st Run :
     Name  Roll Skills
3  Subha    51  Study
2nd Run :
    Name  Roll  Skills
1  Site    31  Travel
3rd Run :
     Name  Roll Skills
3  Subha    51  Study

In [23]:
data.sample(3)

     Name  Roll   Skills
4  Bhagya    61   Foodie
1    Site    31   Travel
0   Arjun    21  Cooking

In [24]:
data['Roll'][0] = 21

C:\Users\murmu\AppData\Local\Temp\ipykernel_4188\382341857.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  data['Roll'][0] = 21
C:\Users\murmu\AppData\Local\Temp\ipykernel_4188\382341857.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Roll'][0] = 21

In [57]:
print(data)

     Name  Roll    Skills
0   Arjun    21   Cooking
1    Site    31    Travel
2    Hari    41  Sleeping
3   Subha    51     Study
4  Bhagya    61    Foodie

In [61]:
# Rename 
data = data.rename(columns={'Roll' : 'Roll_Number'})
data

     Name  Roll_Number    Skills
0   Arjun           21   Cooking
1    Site           31    Travel
2    Hari           41  Sleeping
3   Subha           51     Study
4  Bhagya           61    Foodie

In [67]:
df = pd.DataFrame(DF)

In [65]:
# set_index
data.set_index('Roll_Number', inplace=True)
data

               Name    Skills
Roll_Number
21            Arjun   Cooking
31             Site    Travel
41             Hari  Sleeping
51            Subha     Study
61           Bhagya    Foodie

In [75]:
# Here Roll Number treat as a index number.
print(data.Name[31])
print(data.Name[41])
print(data.Name[51])

Site
Hari
Subha

In [76]:
data.reset_index()

   Roll_Number    Name    Skills
0           21   Arjun   Cooking
1           31    Site    Travel
2           41    Hari  Sleeping
3           51   Subha     Study
4           61  Bhagya    Foodie

In [3]:
DF1 = pd.DataFrame({'Days' : [2,5,7,8,18],
    'Place': ['Puri','Manali','Goa','Puri','Bali'],
     'Visitora': [5590,5000,4895,2500,3400],
       'Mode' : ['Bus','Train','Bus','Bike','Cycle']
     })
DF1

   Days   Place  Visitora   Mode
0     2    Puri      5590    Bus
1     5  Manali      5000  Train
2     7     Goa      4895    Bus
3     8    Puri      2500   Bike
4    18    Bali      3400  Cycle