## Date : 26.09.26

In [3]:
# Import Pandas
import numpy as np
import pandas as pd

In [26]:
DF1 = pd.DataFrame({'Days' : [2,5,7,8,18],
    'Place': ['Puri','Manali','Goa','Puri','Bali'],
     'Visitor': [5590,5000,4895,2500,3400],
       'Mode' : ['Bus','Train','Bus','Bike','Cycle']
     })
DF1

   Days   Place  Visitor   Mode
0     2    Puri     5590    Bus
1     5  Manali     5000  Train
2     7     Goa     4895    Bus
3     8    Puri     2500   Bike
4    18    Bali     3400  Cycle

In [27]:
# to check the shape of DataFrame
DF1.shape

(5, 4)

In [28]:
DF1.info

<bound method DataFrame.info of    Days   Place  Visitor   Mode
0     2    Puri     5590    Bus
1     5  Manali     5000  Train
2     7     Goa     4895    Bus
3     8    Puri     2500   Bike
4    18    Bali     3400  Cycle>

In [29]:
DF1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Days     5 non-null      int64
 1   Place    5 non-null      object
 2   Visitor  5 non-null      int64
 3   Mode     5 non-null      object
dtypes: int64(2), object(2)
memory usage: 292.0+ bytes

In [30]:
# To check the null values 
DF1.isnull()

    Days  Place  Visitor   Mode
0  False  False    False  False
1  False  False    False  False
2  False  False    False  False
3  False  False    False  False
4  False  False    False  False

In [31]:
# check the null value each columns 
DF1.isnull().sum()

Days       0
Place      0
Visitor    0
Mode       0
dtype: int64

In [32]:
# to check DataTypes 
DF1.dtypes

Days        int64
Place      object
Visitor     int64
Mode       object
dtype: object

In [33]:
# unique: 
DF1.Place.unique()

array(['Puri', 'Manali', 'Goa', 'Bali'], dtype=object)

In [34]:
DF1.Visitor.max()

5590

In [37]:
DF1.Visitor.mean()

4277.0

In [41]:
# Describe : Retuns statical count
DF1.describe()

            Days      Visitor
count   5.000000     5.000000
mean    8.000000  4277.000000
std     6.041523  1280.183581
min     2.000000  2500.000000
25%     5.000000  3400.000000
50%     7.000000  4895.000000
75%     8.000000  5000.000000
max    18.000000  5590.000000

In [44]:
# show all columns
DF1.describe(include='all')

             Days Place      Visitor Mode
count    5.000000     5     5.000000    5
unique        NaN     4          NaN    4
top           NaN  Puri          NaN  Bus
freq          NaN     2          NaN    2
mean     8.000000   NaN  4277.000000  NaN
std      6.041523   NaN  1280.183581  NaN
min      2.000000   NaN  2500.000000  NaN
25%      5.000000   NaN  3400.000000  NaN
50%      7.000000   NaN  4895.000000  NaN
75%      8.000000   NaN  5000.000000  NaN
max     18.000000   NaN  5590.000000  NaN

In [49]:
# describe the objects columns
DF1.describe(include='O')

       Place Mode
count      5    5
unique     4    4
top     Puri  Bus
freq       2    2

### to replace null values

In [55]:
DF2 = pd.DataFrame({'Days' : [2,5,np.nan,8,18],
    'Place': ['Puri','Manali','Goa','Puri',np.nan],
     'Visitor': [5590,5000,4895,2500,3400],
       'Mode' : ['Bus','Train','Bus','Bike','Cycle']
     })
DF2

   Days   Place  Visitor   Mode
0   2.0    Puri     5590    Bus
1   5.0  Manali     5000  Train
2   NaN     Goa     4895    Bus
3   8.0    Puri     2500   Bike
4  18.0     NaN     3400  Cycle

In [56]:
DF2.shape

(5, 4)

In [57]:
DF2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Days     4 non-null      float64
 1   Place    4 non-null      object
 2   Visitor  5 non-null      int64
 3   Mode     5 non-null      object
dtypes: float64(1), int64(1), object(2)
memory usage: 292.0+ bytes

In [59]:
DF2.isnull()

    Days  Place  Visitor   Mode
0  False  False    False  False
1  False  False    False  False
2   True  False    False  False
3  False  False    False  False
4  False   True    False  False

In [58]:
DF2.isnull().sum()

Days       1
Place      1
Visitor    0
Mode       0
dtype: int64

In [64]:
DF2.dtypes

Days       float64
Place       object
Visitor      int64
Mode        object
dtype: object

In [65]:
# fillna :  if null value then we have to use fillna
# replace : if special charactet then we have to use replace

In [61]:
DF2.describe(include='all')

             Days Place      Visitor Mode
count    4.000000     4     5.000000    5
unique        NaN     3          NaN    4
top           NaN  Puri          NaN  Bus
freq          NaN     2          NaN    2
mean     8.250000   NaN  4277.000000  NaN
std      6.946222   NaN  1280.183581  NaN
min      2.000000   NaN  2500.000000  NaN
25%      4.250000   NaN  3400.000000  NaN
50%      6.500000   NaN  4895.000000  NaN
75%     10.500000   NaN  5000.000000  NaN
max     18.000000   NaN  5590.000000  NaN

In [73]:
# fillna-used to replace the null values
# in case of numeric column we replace 'nan' with mean/Avg
DF2.Days = DF2.Days.fillna(8.250000)

In [74]:
DF2

    Days   Place  Visitor   Mode
0   2.00    Puri     5590    Bus
1   5.00  Manali     5000  Train
2   8.25     Goa     4895    Bus
3   8.00     Goa     2500   Bike
4  18.00    Puri     3400  Cycle

In [71]:
DF2.Place = DF2.Place.fillna('Puri')

In [72]:
DF2

    Days   Place  Visitor   Mode
0   2.00    Puri     5590    Bus
1   5.00  Manali     5000  Train
2   8.25     Goa     4895    Bus
3   8.00     Goa     2500   Bike
4  18.00    Puri     3400  Cycle

In [77]:
DF2.isnull().sum()

Days       0
Place      0
Visitor    0
Mode       0
dtype: int64

In [81]:
DF3 = pd.DataFrame({'Days' : [2,5,7,8,18],
    'Place': ['Puri','Manali','Goa','Puri','?'],
     'Visitor': [5590,5000,4895,"?",3400],
       'Mode' : ['Bus','Train','Bus','Bike','Cycle']
     })
DF3

   Days   Place Visitor   Mode
0     2    Puri    5590    Bus
1     5  Manali    5000  Train
2     7     Goa    4895    Bus
3     8    Puri       ?   Bike
4    18       ?    3400  Cycle

In [83]:
DF3.shape

(5, 4)

In [84]:
DF3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Days     5 non-null      int64
 1   Place    5 non-null      object
 2   Visitor  5 non-null      object
 3   Mode     5 non-null      object
dtypes: int64(1), object(3)
memory usage: 292.0+ bytes

In [88]:
DF3.dtypes

Days        int64
Place      object
Visitor    object
Mode       object
dtype: object

In [89]:
DF3.isnull().sum()

Days       0
Place      0
Visitor    0
Mode       0
dtype: int64

In [92]:
# unique
DF3.Place.unique()

array(['Puri', 'Manali', 'Goa', '?'], dtype=object)

In [96]:
DF3.Visitor.unique()

array([5590, 5000, 4895, '?', 3400], dtype=object)

In [91]:
DF3.describe(include='all')

             Days Place  Visitor Mode
count    5.000000     5      5.0    5
unique        NaN     4      5.0    4
top           NaN  Puri   5590.0  Bus
freq          NaN     2      1.0    2
mean     8.000000   NaN      NaN  NaN
std      6.041523   NaN      NaN  NaN
min      2.000000   NaN      NaN  NaN
25%      5.000000   NaN      NaN  NaN
50%      7.000000   NaN      NaN  NaN
75%      8.000000   NaN      NaN  NaN
max     18.000000   NaN      NaN  NaN

In [97]:
DF3.Place = DF3.Place.replace('?','Puri')

In [98]:
DF3

   Days   Place Visitor   Mode
0     2    Puri    5590    Bus
1     5  Manali    5000  Train
2     7     Goa    4895    Bus
3     8    Puri       ?   Bike
4    18    Puri    3400  Cycle

In [99]:
# in case of "?" in numeric column
# replace "?" with np.nan
DF3.Visitor = DF3.Visitor.replace('?',np.nan)

C:\Users\murmu\AppData\Local\Temp\ipykernel_9844\2726796030.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  DF3.Visitor = DF3.Visitor.replace('?',np.nan)

In [100]:
DF3

   Days   Place  Visitor   Mode
0     2    Puri   5590.0    Bus
1     5  Manali   5000.0  Train
2     7     Goa   4895.0    Bus
3     8    Puri      NaN   Bike
4    18    Puri   3400.0  Cycle

In [103]:
DF3.dtypes

Days         int64
Place       object
Visitor    float64
Mode        object
dtype: object

In [104]:
DF3.describe(include='all')

             Days Place      Visitor Mode
count    5.000000     5     4.000000    5
unique        NaN     3          NaN    4
top           NaN  Puri          NaN  Bus
freq          NaN     3          NaN    2
mean     8.000000   NaN  4721.250000  NaN
std      6.041523   NaN   932.437442  NaN
min      2.000000   NaN  3400.000000  NaN
25%      5.000000   NaN  4521.250000  NaN
50%      7.000000   NaN  4947.500000  NaN
75%      8.000000   NaN  5147.500000  NaN
max     18.000000   NaN  5590.000000  NaN

In [105]:
DF3.Visitor = DF3.Visitor.fillna(4721)

In [106]:
DF3

   Days   Place  Visitor   Mode
0     2    Puri   5590.0    Bus
1     5  Manali   5000.0  Train
2     7     Goa   4895.0    Bus
3     8    Puri   4721.0   Bike
4    18    Puri   3400.0  Cycle