## Pokemon

In [2]:
import numpy as np
import pandas as pd

In [42]:
pokemon = pd.read_csv(r"C:\Users\murmu\Desktop\MCCAI\Numpy_panda\pokemon.csv")
pokemon

,Name,Type 1,Type 2,Combat Power,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
4,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
146,Dratini,Dragon,NaN,300,41,64,45,50,50,50,1,False
147,Dragonair,Dragon,NaN,420,61,84,65,70,70,70,1,False
148,Dragonite,Dragon,Flying,600,91,134,95,100,100,80,1,False
149,Mewtwo,Psychic,NaN,680,106,110,90,154,90,130,1,True
150,Mew,Psychic,NaN,600,100,100,100,100,100,100,1,True

In [43]:
pokemon.dtypes

Name            object
Type 1          object
Type 2          object
Combat Power     int64
HP               int64
Attack           int64
Defense          int64
Sp. Atk          int64
Sp. Def          int64
Speed            int64
Generation       int64
Legendary         bool
dtype: object

In [44]:
pokemon.isnull().sum()

Name             0
Type 1           0
Type 2          84
Combat Power     0
HP               0
Attack           0
Defense          0
Sp. Atk          0
Sp. Def          0
Speed            0
Generation       0
Legendary        0
dtype: int64

In [45]:
pokemon.describe(include='all')

,Name,Type 1,Type 2,Combat Power,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
count,151,151,67,151.00000,151.000000,151.000000,151.000000,151.000000,151.000000,151.000000,151.0,151
unique,151,15,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
top,Bulbasaur,Water,Poison,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
freq,1,28,19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,146
mean,NaN,NaN,NaN,407.07947,64.211921,72.549669,68.225166,67.139073,66.019868,69.000000,1.0,NaN
std,NaN,NaN,NaN,99.74384,28.590117,26.596162,26.916704,28.534199,24.197926,26.935726,0.0,NaN
min,NaN,NaN,NaN,195.00000,10.000000,5.000000,5.000000,15.000000,20.000000,15.000000,1.0,NaN
25%,NaN,NaN,NaN,320.00000,45.000000,51.000000,50.000000,45.000000,49.000000,46.500000,1.0,NaN
50%,NaN,NaN,NaN,405.00000,60.000000,70.000000,65.000000,65.000000,65.000000,70.000000,1.0,NaN
75%,NaN,NaN,NaN,490.00000,80.000000,90.000000,84.000000,87.500000,80.000000,90.000000,1.0,NaN
max,NaN,NaN,NaN,680.00000,250.000000,134.000000,180.000000,154.000000,125.000000,150.000000,1.0,NaN

In [46]:
pokemon.head()

,Name,Type 1,Type 2,Combat Power,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
4,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False

In [47]:
pokemon.columns = ['Name','Type_1','Type_2','Combat_Power','HP','Attack','Defense','Sp_Atk','Sp_Def','Speed','Generation','Legendary']
pokemon.head()

,Name,Type_1,Type_2,Combat_Power,HP,Attack,Defense,Sp_Atk,Sp_Def,Speed,Generation,Legendary
0,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
4,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False

In [48]:
# pokemon.Type_2 = pokemon.Type_2.replace(np.nan, 'Poison')
pokemon.Type_2 = pokemon.Type_2.fillna('Poison')

In [49]:
pokemon.isnull().sum()

Name            0
Type_1          0
Type_2          0
Combat_Power    0
HP              0
Attack          0
Defense         0
Sp_Atk          0
Sp_Def          0
Speed           0
Generation      0
Legendary       0
dtype: int64

In [50]:
pokemon.Type_2.dtypes

dtype('O')

In [51]:
pokemon

,Name,Type_1,Type_2,Combat_Power,HP,Attack,Defense,Sp_Atk,Sp_Def,Speed,Generation,Legendary
0,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,Charmander,Fire,Poison,309,39,52,43,60,50,65,1,False
4,Charmeleon,Fire,Poison,405,58,64,58,80,65,80,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
146,Dratini,Dragon,Poison,300,41,64,45,50,50,50,1,False
147,Dragonair,Dragon,Poison,420,61,84,65,70,70,70,1,False
148,Dragonite,Dragon,Flying,600,91,134,95,100,100,80,1,False
149,Mewtwo,Psychic,Poison,680,106,110,90,154,90,130,1,True
150,Mew,Psychic,Poison,600,100,100,100,100,100,100,1,True

In [41]:
pokemon

,Name,Type_1,Type_2,Combat_Power,HP,Attack,Defense,Sp_Atk,Sp_Def,Speed,Generation,Legendary
0,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,Charmander,Fire,Poison,309,39,52,43,60,50,65,1,False
4,Charmeleon,Fire,Poison,405,58,64,58,80,65,80,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
146,Dratini,Dragon,Poison,300,41,64,45,50,50,50,1,False
147,Dragonair,Dragon,Poison,420,61,84,65,70,70,70,1,False
148,Dragonite,Dragon,Flying,600,91,134,95,100,100,80,1,False
149,Mewtwo,Psychic,Poison,680,106,110,90,154,90,130,1,True
150,Mew,Psychic,Poison,600,100,100,100,100,100,100,1,True